import type { Component } from 'vue'
import {
  Activity,
  Baby,
  BookOpen,
  Car,
  Droplets,
  Dumbbell,
  Gamepad2,
  Heart,
  Home,
  LayoutGrid,
  Monitor,
  Package,
  Phone,
  Printer,
  Shirt,
  ShoppingCart,
  Sparkles,
  Train,
  Users,
  Utensils,
} from 'lucide-vue-next'
import { markRaw } from 'vue'

export const CATEGORY_ICON: Record<string, Component> = {
  餐飲: markRaw(Utensils),
  購物: markRaw(ShoppingCart),
  服飾: markRaw(Shirt),
  日用: markRaw(Package),
  數碼: markRaw(Monitor),
  美妝: markRaw(Sparkles),
  護膚: markRaw(Droplets),
  應用軟件: markRaw(LayoutGrid),
  住房: markRaw(Home),
  交通: markRaw(Train),
  娛樂: markRaw(Gamepad2),
  醫療: markRaw(Activity),
  通訊: markRaw(Phone),
  汽車: markRaw(Car),
  學習: markRaw(BookOpen),
  辦公: markRaw(Printer),
  運動: markRaw(Dumbbell),
  社交: markRaw(Users),
  人情: markRaw(Heart),
  育兒: markRaw(Baby),
}
